services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: sams-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: sams
      RABBITMQ_DEFAULT_PASS: sams
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'status']
      interval: 10s
      timeout: 5s
      retries: 10
